---
# vim:ft=yaml.ansible
- hosts: all
  name: Everything
  become: true

  roles:
    - role: monolithprojects.homebrew
    # - role: ableton.rustup_init
    - role: packages
    - role: system
    - role: geerlingguy.pip
    - role: geerlingguy.docker
