---
# vim:ft=yaml.ansible
- hosts: all
  name: Everything
  become: true

  roles:
    - role: monolithprojects.homebrew
    - role: packages
      tags: packages
    - role: system
      tags: system
    - role: backups
      tags: backups
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: spotify
      tags: spotify
      when: "'servers' not in group_names"
    - role: firefox
      tags: firefox
      when: "'servers' not in group_names"

    # - role: ableton.rustup_init
