---
# vim:ft=yaml.ansible
- hosts: all
  name: Everything
  become: true

  roles:
    - role: spotify
      tags: spotify
    - role: monolithprojects.homebrew
    - role: packages
      tags: packages
    - role: system
      tags: system
    - role: backups
      tags: backups
    - role: geerlingguy.pip
    - role: geerlingguy.docker

    # - role: ableton.rustup_init
