# vim:ft=yaml.ansible
---
- hosts: all
  name: Everything
  become: true # use root

  vars:
    foo: bar

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted

  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

    - name: Install essential packages
      dnf:
        name: "{{ packages }}"
        state: present

    - name: Make sure crond is started
      service:
        name: crond
        state: started
        enabled: true

    - name: Disable SSH password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication no"
      register: sshd_config
      notify: Restart sshd

    - name: Enable passwordless sudo for {{ username }}
      lineinfile:
        dest: /etc/sudoers
        regexp: "^wheel"
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"

    - name: Suppress login message (hushlogin)
      file:
        path: "/home/{{ username }}/.hushlogin"
        mode: 0644
        owner: "{{ username }}"
        group: "{{ username }}"
        state: touch

    - name: Install Python and python3-pip
      package:
        name:
          - python3
          - python3-pip
        state: present
