- name: Configuring DNF
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      max_parallel_downloads=10
      fastestmirror=True
      defaultTrue=yes
      defaultyes=True

- name: Enable the RPM Fusion repository
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Add DNF repos
  dnf:
    enablerepo:
      [
        "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm",
        "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm",
        "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm ",
        "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm",
      ]
- name: dnf copr repo stuff
  community.general.copr:
    name: "{{ item }}"
    state: "enabled"
  loop: "{{ packages_copr }}"

- name: Install dnf-automatic.
  dnf:
    name: dnf-automatic
    state: present

- name: Ensure dnf-automatic is running and enabled on boot.
  service:
    name: dnf-automatic-install.timer
    state: started
    enabled: yes
# - name: Install desktop packages
#   dnf:
#     name:
#       - "{{ packages_desktop }}"
#       # - "@Development tools"
#       # - "https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm"
#       # - sound-and-video
#       # - 'gstreamer1-plugins-{bad-\*,good-\*,ugly-\*,base} gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel ffmpeg gstreamer-ffmpeg'
#       # - 'lame\* --exclude=lame-devel'
#     state: present
#
