---
# vim:ft=yaml.ansible
username: rdkang

timezone: Europe/London

ntp_timezone: "{{ timezone }}"

locale: en_GB.UTF-8

keyboard_layout: gb

shell: /usr/bin/zsh

dotfiles_repo: https://github.com/rdkang/dotfiles

pip_install_packages:
  - name: docker

docker_users:
  - "{{ username }}"
docker_install_compose: true
docker_edition: "ce"
docker_packages:
  - "docker-{{ docker_edition }}"
  - "docker-{{ docker_edition }}-cli"
  - "docker-{{ docker_edition }}-rootless-extras"
docker_packages_state: present
docker_yum_repo_enable_nightly: "1"

packages_desktop:
  - anki
  - chromium
  - firewall-config
  - gamemode
  - gnome-extensions-app
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-pop-shell
  - gnome-tweaks
  - goverlay
  - kitty
  - kvantum
  - mpv
  - steam
  - sxhkd
  - vlc
  - wl-clipboard
  - adw-gtk3
  - nsxiv
  - bibata-cursor-themes

packages_terminal:
  - zsh
  - cowsay
  - lolcat
  - xclip
  - wireguard-tools
  - vim
  - meson
  - lsd
  - xprop
  - zoxide
  - systemd-devel
  - tealdeer
  - thinkfan
  - tmux
  - trash-cli
  - util-linux-user
  - stress
  - speedtest-cli
  - rofi
  - ncmpcpp
  - neofetch
  - neovim
  - nnn
  - npm
  - openssl
  - openssl1.1
  - pkg-config
  - python-rich
  - lazygit
  - libappindicator
  - libgda
  - libgda-sqlite
  - libstdc++-static
  - lm_sensors
  - hyperfine
  - gcc-c++
  - git-delta
  - git-extras
  - fish
  - fuse-sshfs
  - fzf
  - dateutils
  - dbus-devel
  - ddcutil
  - duf
  - fd-find
  - ansible-lint
  - apprise
  - bat
  - borgmatic
  - ImageMagick

packages_essential:
  - rpmfusion-free-release-tainted
  - dnf-plugins-core
  - curl
  - cabextract
  - xorg-x11-font-utils
  - fontconfig
  - gstreamer1-plugin-openh264
  - mozilla-openh264
  - libdvdcss
  - python3
  - python3-pip

packages_homebrew:
  - yadm
  - "jesseduffield/lazydocker/lazydocker"
  - tmuxinator
  - atuin
  - commitizen
  - commitlint
  - rga
  - spotifyd
  - watchexec

packages_copr:
  # - "copr.fedorainfracloud.org/coprs/mamg22/nsxiv"
  # - "@atim/lazygit"
  # - "@peterwu/rendezvous"
  # - "@nickavem/adw-gtk3"
