---
# vim:ft=yaml.ansible
username: rdkang

timezone: Europe/London

ntp_timezone: "{{ timezone }}"

locale: en_GB.UTF-8

keyboard_layout: gb

shell: /usr/bin/zsh

dotfiles_repo: https://github.com/rdkang/dotfiles

laptop_hostname: asahipad

pip_install_packages:
  - name: docker
  - name: bdfr

docker_users:
  - "{{ username }}"
docker_install_compose: true
docker_edition: "ce"
docker_packages:
  - "docker-{{ docker_edition }}"
  - "docker-{{ docker_edition }}-cli"
  - "docker-{{ docker_edition }}-rootless-extras"
docker_packages_state: present
# docker_yum_repo_enable_nightly: "1"

packages_essential:
  - rpmfusion-free-release-tainted
  - dnf-plugins-core
  - curl
  - cabextract
  - xorg-x11-font-utils
  - fontconfig
  - gstreamer1-plugin-openh264
  - mozilla-openh264
  - libdvdcss
  - openssl
  - openssl1.1
  - gcc-c++
  - libstdc++-static
  - xset

packages_cli:
  - ImageMagick
  - android-tools
  - ansible-lint
  - apprise
  - bat
  - borgmatic
  - dateutils
  - ddcutil
  - duf
  - fd-find
  - firewall-config
  - fish
  - fuse-sshfs
  - fzf
  - git-delta
  - git-extras
  - hugo
  - hyperfine
  - lazygit
  - lm_sensors
  - lsd
  - mpv
  - ncmpcpp
  - neofetch
  - neovim
  - nnn
  - npm
  - perl-Image-ExifTool
  - powertop
  - python-rich
  - speedtest-cli
  - stress
  - systemd-devel
  - tealdeer
  - thinkfan
  - tmux
  - trash-cli
  - cowsay
  - util-linux-user
  - vim
  - wireguard-tools
  - wl-clipboard
  - xclip
  - xprop
  - zoxide
  - zsh
  - neovim

packages_desktop:
  - chromium
  - gnome-extensions-app
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-pop-shell
  - gnome-tweaks
  - goverlay
  - kitty
  - kvantum
  - libappindicator
  - libgda
  - libgda-sqlite
  - meson
  - pkg-config
  - rofi
  - steam
  - sxhkd
  - vlc
  - adw-gtk3
  - nsxiv
  - bibata-cursor-themes
  - fuse-emulator
  - mpv-mpris

packages_gaming:
  - dbus-devel
  - gamemode

packages_homebrew:
  - yadm
  - "jesseduffield/lazydocker/lazydocker"
  - tmuxinator
  - atuin
  - commitizen
  - commitlint
  - rga
  - spotifyd
  - watchexec

packages_cargo:
  - dust
  - cargo-update

packages_copr:
  - "mamg22/nsxiv"
  - "atim/lazygit"
  - "peterwu/rendezvous"
  - "nickavem/adw-gtk3"

packages_flatpak:
  - org.gimp.GIMP
  - org.inkscape.Inkscape
  - com.github.iwalton3.jellyfin-media-player
  - com.mattjakeman.ExtensionManager
  - com.spotify.Client
  - md.obsidian.Obsidian
  - io.github.Foldex.AdwSteamGtk
  - org.gtk.Gtk3theme.adw-gtk3
  - org.gtk.Gtk3theme.adw-gtk3-dark
  - net.ankiweb.Anki
  - org.onlyoffice.desktopeditors
  - dev.geopjr.Collision
  - fr.romainvigier.MetadataCleaner
  - net.hovancik.Stretchly
  - com.github.iwalton3.jellyfin-mpv-shim
