# https://docs.ansible.com/ansible/latest/collections/ansible/posix/firewalld_module.html
- name: open ports for kdeconnect
  ansible.posix.firewalld:
    port: 1716-1764/tcp,1716-1764/udp
    zone: home
    permanent: yes
    immediate: yes
    state: enabled
  when: "'servers' not in group_names"
