---
# vim:ft=yaml.ansible
#
- name: Setup ssh
  include_tasks: ssh.yml

- name: Installs and updates packages
  include_tasks: packages.yml
  # tags: packages

- name: Makes sure system services are running
  include_tasks: services.yml

- name: Sets up tmux
  include_tasks: tmux.yml

- name: Sets up users
  include_tasks: users.yml

- name: Sets up cron jobs
  include_tasks: cron.yml
