# vim:ft=yaml.ansible
#

- name: Configuring DNF
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      max_parallel_downloads=10
      fastestmirror=True
      defaultTrue=yes
      defaultyes=True

- name: Add DNF repos
  dnf:
    enablerepo:
      [
        "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm",
        "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm",
        "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm ",
        "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm",
      ]

# FIX: this
# - name: DNF copr repos
#   tags: copr
#   community.general.copr:
#     name: "{{ packages_copr }}"
#     state: "enabled"

- name: Install essential packages
  dnf:
    name: "{{ packages_essential }}"
    state: present

- name: Install cli packages
  dnf:
    name: "{{ packages_cli }}"
    state: present

- name: Install gaming packages
  dnf:
    name: "{{ packages_gaming }}"
    state: present
  when: "'servers' not in group_names"

- name: Install desktop packages
  dnf:
    name: "{{ packages_desktop }}"
    state: present
  when: "'servers' not in group_names"
# - name: Install desktop packages
#   dnf:
#     name:
#       - "{{ packages_desktop }}"
#       # - "@Development tools"
#       # - "https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm"
#       # - sound-and-video
#       # - 'gstreamer1-plugins-{bad-\*,good-\*,ugly-\*,base} gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel ffmpeg gstreamer-ffmpeg'
#       # - 'lame\* --exclude=lame-devel'
#     state: present
#
- name: Install homebrew packages
  become: false
  community.general.homebrew:
    name: "{{ packages_homebrew }}"
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ packages_flatpak }}"
    state: present
