---
- name: Enable passwordless sudo for {{ username }}
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  when: ansible_hostname == "laptop_hostname"

- name: Creates user of {{ username }}
  user:
    name: "{{ username }}"
    groups:
      - docker
      - users
      - "{{ username }}"
    append: true
    shell: "{{ shell }}"
    # password: "{{ password }}"
    # update_password: on_create

- name: Suppress login message (hushlogin)
  file:
    path: "/home/{{ username }}/.hushlogin"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
    state: touch
